<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4enkvp9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4enkvp9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4enkvp9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4enkvp9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container4enkvp9\srcDevDebugProjectContainer([
    'container.build_hash' => '4enkvp9',
    'container.build_id' => 'a6ec4bf6',
    'container.build_time' => 1561455129,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4enkvp9');
