<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkmu0sl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkmu0sl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNkmu0sl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNkmu0sl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNkmu0sl\srcDevDebugProjectContainer([
    'container.build_hash' => 'Nkmu0sl',
    'container.build_id' => '7183e266',
    'container.build_time' => 1561454787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNkmu0sl');
