<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDf2msg4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDf2msg4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDf2msg4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDf2msg4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDf2msg4\srcDevDebugProjectContainer([
    'container.build_hash' => 'Df2msg4',
    'container.build_id' => '55faf911',
    'container.build_time' => 1561460753,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDf2msg4');
